%% Generated by the Erlang ASN.1 compiler. Version: 5.0.17
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module CREDSSP.

-ifndef(_CREDSSP_HRL_).
-define(_CREDSSP_HRL_, true).

-record('TSRequest', {
  version,
  negoTokens = asn1_NOVALUE,
  authInfo = asn1_NOVALUE,
  pubKeyAuth = asn1_NOVALUE,
  errorCode = asn1_NOVALUE,
  clientNonce = asn1_NOVALUE
}).

-record('NegoData_SEQOF', {
  negoToken
}).

-record('TSCredentials', {
  credType,
  credentials
}).

-record('TSPasswordCreds', {
  domainName,
  userName,
  password
}).

-record('TSSmartCardCreds', {
  pin,
  cspData,
  userHint = asn1_NOVALUE,
  domainHint = asn1_NOVALUE
}).

-record('TSCspDataDetail', {
  keySpec,
  cardName,
  readerName,
  containerName,
  cspName
}).

-record('TSRemoteGuardCreds', {
  logonCred,
  supplementalCreds = asn1_NOVALUE
}).

-record('TSRemoteGuardPackageCred', {
  packageName,
  credBuffer
}).

-endif. %% _CREDSSP_HRL_
